### ISSUE TITLE
Estudar VITE e a possibilidade de fazer o front também em typescript

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-Squad04#11]
# Descrição 
Olhar rapidamente a tecnologia VIT e decidir se há a possibilidade de fazer o Frontend com a mesma.

# Tarefas
[ ] Estudar a tecnologia.

**Comment by StrangeUnit28** [comment]
- Vídeo rápido, mas completo sobre o Vite: https://www.youtube.com/watch?v=KCrXgy8qtjM

- Vídeo mais longo sobre Vite 2.0: https://www.youtube.com/watch?v=LQQ3CR2JTX8

- Alguns ônus da ferramenta, que devem ser levados em consideração:
  1. O Vite até o presente momento ainda **possui alguns bugs então deve ser usado em produção por sua conta e risco.**
  2. O suporte 'direto da caixa' conta que você esteja **escrevendo Javascript moderno**, não oferecendo suporte legado pra IE por padrão.
  3. Vite ainda não possui um bom suporte SSR (Server Side Rendering), ainda é mais recomendado usar meta-frameworks como Next ou Nuxt até um release mais estável.

- É possível fazer o front em TypeScript, uma vez que o Vite é apenas uma ferramenta, o React continuaria sendo o framework principal
